# Generated by Django 2.1.11 on 2020-01-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilmatic_core', '0048_post_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='PittsburghBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='PittsburghEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.event',),
        ),
    ]
