# Generated by Django 2.1.11 on 2020-01-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0048_post_shape'),
        ('pittsburgh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PittsburghPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='councilmatic_core.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('councilmatic_core.person',),
        ),
    ]
